#!/bin/sh
# Run the original public-API Unity suites against the Rust C ABI shim
# (target/release/libcjson_ffi.a) instead of cJSON.c.
#
# Suites: parse_examples parse_with_opts compare_tests cjson_add
#         readme_examples minify_tests misc_tests
# The other suites in tests/CMakeLists.txt (parse_number, parse_hex4,
# parse_string, parse_array, parse_object, parse_value, print_string,
# print_number, print_array, print_object, print_value) test static functions
# of cJSON.c directly (parse_number(), print_value(), printbuffer, ...). A
# library cannot provide those, so they run only against the C (make c-unity).
# Their Rust ports live in cjson-core/tests/.
#
# How it works: the suites are copied unmodified into build/ffi-unity/tests/,
# together with tests/common.h and tests/inputs/. common.h does
# `#include "../cJSON.c"`, and that path resolves to build/ffi-unity/cJSON.c,
# a shim this script generates. The shim contains only:
#   - #include "cJSON.h" (the public header, used unchanged),
#   - the `true` / `false` macros cJSON.c defines (used by the suites),
#   - `internal_hooks` / `global_hooks` = { malloc, free, realloc }, which
#     common.h's reset() calls through `global_hooks.deallocate`. This matches
#     cJSON.c's default hooks, and the Rust shim must allocate with malloc for
#     its default hooks anyway (C callers free() its output),
#   - copies of two static helpers from cJSON.c that the suites call:
#     compare_double() (readme_examples.c) and cJSON_strdup() (misc_tests.c,
#     the aliasing test). Neither is part of the library under test; the
#     suites use them only to compare doubles and to make a heap copy of a
#     string through global_hooks.
#   - `#define add_item_to_array cJSON_AddItemToArray`. misc_tests.c
#     (cjson_functions_should_not_crash_with_null_pointers) calls the static
#     add_item_to_array() directly. cJSON.c:2080-2083 defines the public
#     cJSON_AddItemToArray as exactly `return add_item_to_array(array, item);`,
#     so the mapping keeps the call's meaning and routes it through the Rust
#     library.
# Nothing from cJSON.c's implementation is linked; every cJSON_* call goes
# to libcjson_ffi.a.
#
# Edits to the COPIED files (tests/ itself is never modified):
#   misc_tests.c: these cases are removed, together with their RUN_TEST lines,
#   because they call static internals of cJSON.c that no library exports:
#     - ensure_should_fail_on_failed_realloc (ensure(), printbuffer); the
#       helper failing_realloc, used only by it, is removed as well
#     - skip_utf8_bom_should_skip_bom (skip_utf8_bom(), parse_buffer)
#     - skip_utf8_bom_should_not_skip_bom_if_not_at_beginning (same)
#   All three are ported as Rust tests with the same names in
#   cjson-core/tests/misc_tests.rs, and the BOM behavior is also covered by the
#   tests/parity/bom_* fixtures.
#   cjson_add_item_to_object_should_not_use_after_free_when_string_is_aliased
#   is NOT edited. It calls cJSON_strdup(..., &global_hooks), which the shim
#   provides with cJSON.c's semantics (a malloc'd copy). That keeps the test's
#   meaning: the key is a heap string the library later frees with free().
# The script checks that exactly 4 functions and 3 RUN_TEST lines were
# removed, and fails otherwise.
#
# Environment (set by `make ffi-unity`): CC, CFLAGS, FFI_LIB, FFI_LDLIBS.
set -eu

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT"

CC=${CC:-cc}
CFLAGS=${CFLAGS:-}
FFI_LIB=${FFI_LIB:-target/release/libcjson_ffi.a}
FFI_LDLIBS=${FFI_LDLIBS:--lm}
OUT=build/ffi-unity
SUITES="parse_examples parse_with_opts compare_tests cjson_add readme_examples minify_tests misc_tests"

if [ ! -f "$FFI_LIB" ]; then
    echo "ffi-unity: $FFI_LIB not found (run: make ffi-lib)" >&2
    exit 1
fi

rm -rf "$OUT"
mkdir -p "$OUT/tests/inputs"
cp tests/common.h "$OUT/tests/"
cp tests/inputs/* "$OUT/tests/inputs/"
for s in $SUITES; do
    cp "tests/$s.c" "$OUT/tests/"
done

cat > "$OUT/cJSON.c" <<'EOF'
/* Generated by tools/ffi-unity/run.sh. Stands in for ../cJSON.c in the copied
   tests/common.h so that the public-API Unity suites link against
   libcjson_ffi.a. See the header of tools/ffi-unity/run.sh. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include <ctype.h>

#include "cJSON.h"

#ifdef true
#undef true
#endif
#define true ((cJSON_bool)1)

#ifdef false
#undef false
#endif
#define false ((cJSON_bool)0)

typedef struct internal_hooks
{
    void *(CJSON_CDECL *allocate)(size_t size);
    void (CJSON_CDECL *deallocate)(void *pointer);
    void *(CJSON_CDECL *reallocate)(void *pointer, size_t size);
} internal_hooks;

static internal_hooks global_hooks = { malloc, free, realloc };

/* cJSON.c:2080-2083: cJSON_AddItemToArray is `return add_item_to_array(array, item);` */
#define add_item_to_array cJSON_AddItemToArray

/* Copy of cJSON.c compare_double. */
static cJSON_bool compare_double(double a, double b)
{
    double maxVal = fabs(a) > fabs(b) ? fabs(a) : fabs(b);
    return (fabs(a - b) <= maxVal * DBL_EPSILON);
}

/* Copy of cJSON.c cJSON_strdup. */
static unsigned char* cJSON_strdup(const unsigned char* string, const internal_hooks * const hooks)
{
    size_t length = 0;
    unsigned char *copy = NULL;

    if (string == NULL)
    {
        return NULL;
    }

    length = strlen((const char*)string) + sizeof("");
    copy = (unsigned char*)hooks->allocate(length);
    if (copy == NULL)
    {
        return NULL;
    }
    memcpy(copy, string, length);

    return copy;
}

/* References the helpers so suites that do not use them build with -Werror. */
void ffi_unity_shim_anchor(void);
void ffi_unity_shim_anchor(void)
{
    (void)global_hooks;
    (void)compare_double;
    (void)cJSON_strdup;
}
EOF

awk '
    BEGIN { skip = 0; funcs = 0; runs = 0 }
    skip == 0 && ($0 ~ /^static void \*CJSON_CDECL failing_realloc\(/ ||
                  $0 ~ /^static void ensure_should_fail_on_failed_realloc\(/ ||
                  $0 ~ /^static void skip_utf8_bom_should_skip_bom\(/ ||
                  $0 ~ /^static void skip_utf8_bom_should_not_skip_bom_if_not_at_beginning\(/) {
        skip = 1; funcs++; next
    }
    skip == 1 { if ($0 ~ /^}/) { skip = 0 } next }
    $0 ~ /RUN_TEST\((ensure_should_fail_on_failed_realloc|skip_utf8_bom_should_skip_bom|skip_utf8_bom_should_not_skip_bom_if_not_at_beginning)\);/ {
        runs++; next
    }
    { print }
    END {
        if (funcs != 4 || runs != 3) {
            printf "ffi-unity: expected to remove 4 functions and 3 RUN_TEST lines from misc_tests.c, removed %d and %d\n", funcs, runs > "/dev/stderr"
            exit 1
        }
    }
' tests/misc_tests.c > "$OUT/tests/misc_tests.c"

if grep -n "ensure(\|skip_utf8_bom\|printbuffer\|parse_buffer" "$OUT/tests/misc_tests.c"; then
    echo "ffi-unity: static internals still referenced in the copied misc_tests.c" >&2
    exit 1
fi

$CC -c tests/unity/src/unity.c -o "$OUT/unity.o"
for s in $SUITES; do
    echo "$CC $CFLAGS -I$ROOT/tests -I$ROOT $OUT/tests/$s.c $OUT/unity.o $FFI_LIB $FFI_LDLIBS -o $OUT/tests/$s"
    # shellcheck disable=SC2086 # CFLAGS and FFI_LDLIBS are word lists
    $CC $CFLAGS -I"$ROOT/tests" -I"$ROOT" "$OUT/tests/$s.c" "$OUT/unity.o" "$FFI_LIB" $FFI_LDLIBS -o "$OUT/tests/$s"
done

failed=""
for s in $SUITES; do
    echo "== ffi-unity: $s"
    if ! (cd "$OUT/tests" && "./$s" > "$s.log" 2>&1); then
        failed="$failed $s"
        grep -a ":FAIL" "$OUT/tests/$s.log" || true
    fi
    tail -n 3 "$OUT/tests/$s.log"
done

if [ -n "$failed" ]; then
    echo "ffi-unity FAILED:$failed"
    exit 1
fi
echo "ffi-unity: all 7 suites passed (misc_tests without the 3 cases listed in tools/ffi-unity/run.sh)"
